includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: Build failed. Leave a comment with 'recheck-ryu' to rerun a check. ('recheck' will be ignored.)
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
          branch: ^master$
        - event: change-restored
          branch: ^master$
        # Change "myvendor" below to your vendor's name to add a custom
        # recheck trigger that runs the check pipeline jobs when someone
        # adds a comment to a review that says "recheck $VENDOR".
        - event: comment-added
          branch: ^master$
          comment: (?i)^(Patch Set [0-9]+:\n\n)?\s*recheck-ryu\s*$
#        - event: comment-added
#          branch: ^master$
#          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( myvendor))\s*$
#    success:
#      gerrit:
#        verified: 1
#    failure:
#      gerrit:
#        verified: 0

jobs:
  - name: ^.*$
    parameter-function: set_log_url
    success-pattern: http://180.37.183.32/ryuci/{build.parameters[LOG_PATH]}
    failure-pattern: http://180.37.183.32/ryuci/{build.parameters[LOG_PATH]}
  - name: ^check-tempest-dsvm.*$
    parameter-function: single_use_node

projects:
  - name: openstack/neutron
    check:
      - check-tempest-dsvm-ryuplugin
      - check-tempest-dsvm-ofagent
